Actualidad\ComunBundle\Entity\AdminSesion:
    type: entity
    table: admin_sesion
    indexes:
        IDX_468DD3E2DB38439E:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaIngreso:
            type: datetime
            nullable: true
            column: fecha_ingreso
        fechaRequest:
            type: datetime
            nullable: true
            column: fecha_request
        disponible:
            type: boolean
            nullable: true
    manyToOne:
        usuario:
            targetEntity: AdminUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
