Actualidad\ComunBundle\Entity\AdminGrado:
    type: entity
    table: admin_grado
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
