Actualidad\ComunBundle\Entity\AdminUsuario:
    type: entity
    table: admin_usuario
    indexes:
        IDX_E65932D4E8608214:
            columns:
                - ciudad_id
        IDX_E65932D44E7121AF:
            columns:
                - provincia_id
        IDX_E65932D491A441CC:
            columns:
                - grado_id
        IDX_E65932D44BAB96C:
            columns:
                - rol_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        login:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        clave:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        nombre:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        apellido:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        correo:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        activo:
            type: boolean
            nullable: true
        fechaNacimiento:
            type: date
            nullable: true
            column: fecha_nacimiento
        sector:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        zona:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        foto:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
        fechaModificacion:
            type: datetime
            nullable: true
            column: fecha_modificacion
        cookies:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    manyToOne:
        ciudad:
            targetEntity: AdminCiudad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ciudad_id:
                    referencedColumnName: id
            orphanRemoval: false
        provincia:
            targetEntity: AdminProvincia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                provincia_id:
                    referencedColumnName: id
            orphanRemoval: false
        grado:
            targetEntity: AdminGrado
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                grado_id:
                    referencedColumnName: id
            orphanRemoval: false
        rol:
            targetEntity: AdminRol
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
