Actualidad\ComunBundle\Entity\AdminTutorial:
    type: entity
    table: admin_tutorial
    indexes:
        IDX_52CBF8EFDB38439E:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        pdf:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        video:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
        fecha:
            type: date
            nullable: true
    manyToOne:
        usuario:
            targetEntity: AdminUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
