Actualidad\ComunBundle\Entity\EaPaginaLog:
    type: entity
    table: ea_pagina_log
    indexes:
        IDX_48F4085557991ECF:
            columns:
                - pagina_id
        IDX_48F40855DB38439E:
            columns:
                - usuario_id
        IDX_48F408557D139FE4:
            columns:
                - estatus_pagina_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaInicio:
            type: datetime
            nullable: true
            column: fecha_inicio
        fechaFin:
            type: datetime
            nullable: true
            column: fecha_fin
        porcentajeAvance:
            type: decimal
            nullable: true
            precision: 5
            scale: 2
            column: porcentaje_avance
        fechaInteraccion:
            type: datetime
            nullable: true
            column: fecha_interaccion
    manyToOne:
        pagina:
            targetEntity: EaPagina
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pagina_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: AdminUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
        estatusPagina:
            targetEntity: EaEstatusPagina
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                estatus_pagina_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
