Actualidad\ComunBundle\Entity\EaPrueba:
    type: entity
    table: ea_prueba
    indexes:
        IDX_CE9256DEDB38439E:
            columns:
                - usuario_id
        IDX_CE9256DE57991ECF:
            columns:
                - pagina_id
        IDX_CE9256DE64373B63:
            columns:
                - estatus_contenido_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 350
            options:
                fixed: false
        cantidadPreguntas:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: cantidad_preguntas
        cantidadMostrar:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: cantidad_mostrar
        duracion:
            type: time
            nullable: true
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
        fechaModificacion:
            type: datetime
            nullable: true
            column: fecha_modificacion
        minCorrectas:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: min_correctas
        maxIntentos:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: max_intentos
    manyToOne:
        usuario:
            targetEntity: AdminUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
        pagina:
            targetEntity: EaPagina
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pagina_id:
                    referencedColumnName: id
            orphanRemoval: false
        estatusContenido:
            targetEntity: EaEstatusContenido
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                estatus_contenido_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
