_paginasEvaluacion:
    path:     /paginas
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:index }

_editEvaluacion:
    path:     /edit/{prueba_id}
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:edit, prueba_id: 0 }

_preguntas:
    path:     /preguntas/{prueba_id}
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:preguntas }

_editPregunta:
    path:     /editPregunta/{prueba_id}/{pregunta_id}/{cantidad}/{total}
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:editPregunta, pregunta_id: 0, cantidad: 1, total: 1 }

_editInteractivo:
    path:     /editInteractivo/{pregunta_id}/{cantidad}/{total}
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:editInteractivo, pregunta_id: 0, cantidad: 1, total: 1 }

_opciones:
    path:     /opciones/{pregunta_id}/{cantidad}/{total}
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:opciones }

_verEvaluacionInteractivo:
    path:     /verEvaluacionInteractivo/{pregunta_id}/{reset}
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:verEvaluacionInteractivo, reset: 0 }

_ajaxEditOpcion:
    path:     /ajaxEditOpcion
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:ajaxEditOpcion }
    requirements:
        _method: GET

_ajaxUpdateOpcion:
    path:     /ajaxUpdateOpcion
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:ajaxUpdateOpcion }
    requirements:
        _method: POST

_ajaxCorrecta:
    path:     /ajaxCorrecta
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:ajaxCorrecta }
    requirements:
        _method: POST

_ajaxDeleteOpcion:
    path:     /ajaxDeleteOpcion
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:ajaxDeleteOpcion }
    requirements:
        method: POST

_ajaxCodigoEvaluacion:
    path:     /ajaxCodigoEvaluacion
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:ajaxCodigoEvaluacion }
    requirements:
        _method: POST

_ajaxTryCase:
    path:     /ajaxTryCase
    defaults: { _controller: ActualidadBackendBundle:Evaluacion:ajaxTryCase }
    requirements:
        _method: POST
